GoDinghy.app/Controllers/ContactpageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoDinghy.app.Classes.Helpers;
using GoDinghy.app.Models;
using GoDinghy.app.Models.Helpers;
using Umbraco.Web;

namespace GoDinghy.app.Controllers
{
    public class ContactpageController : MasterController
    {
        // GET: Contactpage
        public ActionResult Contactpage()
        {
            var model = new ContactpageModel();
            model.Banner = MediaHelper.GetMediaUrl(CurrentPage, "bannerImage");
            model.Header = CurrentPage.GetPropertyValue<string>("header");
            model.CompanyAddress = CurrentPage.GetPropertyValue<IHtmlString>("companyAddress");
            model.CompanyPhone = CurrentPage.GetPropertyValue<string>("companyPhone");
            model.CompanyEmail = CurrentPage.GetPropertyValue<string>("companyEmail");

            model.Contactform = new ContactformModel() {NodeId = CurrentPage.Id};
            model.ThanksHeader = CurrentPage.GetPropertyValue<string>("thanksHeader");
            model.ThanksBodytext = CurrentPage.GetPropertyValue<IHtmlString>("thanksMessage");

            return View(model);
        }
    }
}

GoDinghy.app/Controllers/CustomerListPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoDinghy.app.Models;
using Umbraco.Web;

namespace GoDinghy.app.Controllers
{
    public class CustomerListPageController : MasterController
    {
        // GET: CustomerListPage
        public ActionResult CustomerListPage()
        {
            var model = new CustomerListPageModel();
            model.Header = CurrentPage.GetPropertyValue<string>("header");
            model.Bodytext = CurrentPage.GetPropertyValue<IHtmlString>("bodytext");

            return View(model);
        }
    }
}

GoDinghy.app/Controllers/EmployeepageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoDinghy.app.Models;
using GoDinghy.app.Classes.Helpers;
using Umbraco.Web;

namespace GoDinghy.app.Controllers
{
    public class EmployeepageController : MasterController
    {
        // GET: Employeepage
        public ActionResult Employeepage()
        {
            var model = new EmployeepageModel();
            model.Image = MediaHelper.GetMediaUrl(CurrentPage, "image");
            model.Name = CurrentPage.GetPropertyValue<string>("employeeName");
            model.Title = CurrentPage.GetPropertyValue<string>("employeeTitle");
            model.Email = CurrentPage.GetPropertyValue<string>("employeeEmail");
            model.Phone = CurrentPage.GetPropertyValue<string>("employeePhone");
            model.Description = CurrentPage.GetPropertyValue<IHtmlString>("employeeDescription");

            return View(model);
        }
    }
}

GoDinghy.app/Controllers/EmployeespageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoDinghy.app.Classes.Helpers;
using GoDinghy.app.Models;
using Umbraco.Web;

namespace GoDinghy.app.Controllers
{
    public class EmployeespageController : MasterController
    {
        // GET: Employeespage
        public ActionResult Employeespage()
        {
            var model = new EmployeespageModel();
            model.Banner = MediaHelper.GetMediaUrl(CurrentPage, "bannerImage");
            model.Header = CurrentPage.GetPropertyValue<string>("header");
            model.Bodytext = CurrentPage.GetPropertyValue<IHtmlString>("bodytext");
            model.Employees = CurrentPage.Children.Select(employee => new EmployeepageModel()
            {
                Url = employee.Url,
                Image = MediaHelper.GetMediaUrl(employee, "image"),
                Name = employee.GetPropertyValue<string>("employeeName"),
                Title = employee.GetPropertyValue<string>("employeeTitle"),
                Email = employee.GetPropertyValue<string>("employeeEmail"),
                Phone = employee.GetPropertyValue<string>("employeePhone")
        });

            return View(model);
        }
    }
}

GoDinghy.app/Controllers/FrontpageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoDinghy.app.Models;
using GoDinghy.app.Classes.Helpers;
using Umbraco.Core.Models;
using Umbraco.Web;

namespace GoDinghy.app.Controllers
{
    public class FrontpageController : MasterController
    {
        // GET: Frontpage
        public ActionResult Frontpage()
        {
            var model = new FrontpageModel();
            model.Banner = MediaHelper.GetMediaUrl(CurrentPage, "bannerImage");
            model.Header = CurrentPage.GetPropertyValue<string>("header");
            model.Teaser = CurrentPage.GetPropertyValue<IHtmlString>("teaser");
            model.Grid = CurrentPage.GetGridHtml("grid");
            return View(model);
        }
    }

    //public string GetUrlOrEmpty(IPublishedContent content)
        //{
        //    return content != null ? content.Url : string.Empty;
        //}
    //}
}

GoDinghy.app/Controllers/MemberpageController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoDinghy.app.Classes.Helpers;
using GoDinghy.app.Models;
using umbraco.cms.businesslogic.member;
using Umbraco.Core.Persistence;
using Umbraco.Web;
using Umbraco.Core.Services;

namespace GoDinghy.app.Controllers
{
    public class MemberpageController : MasterController
    {

        // GET: Memberpage
        public ActionResult Memberpage()
        {
            int currentNode = CurrentPage.Id;
            //var memberService = Services.MemberService;
            //var roles = memberService.GetAllRoles();
            //MemberGroup[] memberGroups = MemberGroup.GetAll;


            var model = new MemberpageModel();
            model.Header = CurrentPage.GetPropertyValue<string>("header");
            model.Bodytext = CurrentPage.GetPropertyValue<IHtmlString>("bodytext");
            model.MemberModel = new CreateMemberModel() {MemberGroups = GetMemberGroups(), NodeId = currentNode};

            return View(model);
        }

        private IEnumerable<SelectListItem> GetMemberGroups()
        {
            MemberGroup[] memberGroups = MemberGroup.GetAll;
            IList<SelectListItem> items = new List<SelectListItem>();
            foreach (var group in memberGroups)
            {
                items.Add(new SelectListItem() { Text = group.Text, Value = group.Text });
            }
            return items;
        }
    }
}

GoDinghy.app/Controllers/Surface/MemberSurfaceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using GoDinghy.app.Classes.Helpers;
using GoDinghy.app.Models;
using GoDinghy.app.Models.Helpers;
using Umbraco.Web.Mvc;

namespace GoDinghy.app.Controllers.Surface
{
    public class MemberSurfaceController : SurfaceController
    {
        private string GetCurrentMenber()
        {
            var username = "";
            var currentMember = Members.GetCurrentMember();
            if (currentMember != null)
            {
                username = currentMember.Name;
            }
            return username;
        }
        // The MemberLogout Action signs out the user and redirects to the site home page:
        [HttpPost]
        public ActionResult MemberLogout()
        {
            Session.Clear();
            FormsAuthentication.SignOut();
            LogfileHelper.MemberLog(GetCurrentMenber(), "Log out at");
            return Redirect("/");
        }

        // The MemberLoginPost Action checks the entered credentials using the standard Asp Net membership provider and redirects the user to the same page. Either as logged in, or with a message set in the TempData dictionary:
        [HttpPost]
        [ActionName("Login")]
        public ActionResult MemberLogin(MemberLoginModel model)
        {
            if (Membership.ValidateUser(model.Username, model.Password))
            {
                FormsAuthentication.SetAuthCookie(model.Username, true);
                LogfileHelper.MemberLog(model.Username, "Log in at");
                return RedirectToCurrentUmbracoPage();
            }
            else
            {
                LogfileHelper.MemberLog(model.Username, "Failed log in at");
                return RedirectToCurrentUmbracoPage();
            }
        }

        [HttpPost]
        public JsonResult SignUp(CreateMemberModel model, int nodeId)
        {
            ApplyFormResponse resultMessage = new ApplyFormResponse();

            if (!ModelState.IsValid) {
                resultMessage.ErrorMessage = "Der er desværre sket en fejl - prøv igen";
                return Json(resultMessage);
            }
            var memberService = Services.MemberService;
            if (memberService.GetByEmail(model.Email) != null)
            {
                resultMessage.ErrorCode = "Member already exists";
                return Json(resultMessage);
            }
            var member = memberService.CreateMemberWithIdentity(model.Username, model.Email, model.Name, "Member");
            memberService.Save(member);
            memberService.AssignRole(member.Id, model.SelectedGroup);
            memberService.SavePassword(member, model.Password);
            resultMessage.ErrorCode = "OK";
            return Json(resultMessage);
        }
        public class ApplyFormResponse
        {
            public string ErrorCode { get; set; }
            public string ErrorMessage { get; set; }
        }
        [HttpPost]
        public JsonResult OpenLogFile()
        {
            var dir = AppDomain.CurrentDomain.BaseDirectory + "/App_Data/Logs";
            var path = Path.Combine(dir, "Login-out-log.txt");
            System.Diagnostics.Process.Start(path);
            return Json("OK");
        }
    }
}

GoDinghy.app/Controllers/TextpageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GoDinghy.app.Classes.Helpers;
using GoDinghy.app.Models;
using Umbraco.Web;

namespace GoDinghy.app.Controllers
{
    public class TextpageController : MasterController
    {
        // GET: Textpage
        public ActionResult Textpage()
        {
            var model = new TextpageModel();
            model.Banner = MediaHelper.GetMediaUrl(CurrentPage, "bannerImage");
            model.Header = CurrentPage.GetPropertyValue<string>("header");
            model.Grid = CurrentPage.GetGridHtml("grid");

            return View(model);
        }
    }
}

GoDinghy.app/Views/Contactpage.cshtml
@model ContactpageModel

<div class="contactpage">
    <div class="container-fluid">
        <div class="banner" style="background-image: url(@Model.Banner)">

        </div>
        <div class="container text-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="text">
                        <h1>@Model.Header</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="box">
                    <h3>Kontaktinformation</h3>
                    @Model.CompanyAddress
                    <p>
                        Telefon: <a href="Tel:@Model.CompanyPhone">@Model.CompanyPhone</a>
                    </p>
                    <p>
                        E-mail: <a href="Mailto:@Model.CompanyEmail">@Model.CompanyEmail</a>
                    </p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="box">
                    <div class="form-bg">
                        <div class="contactform">
                            @Html.Partial("_Contactform", Model.Contactform)
                        </div>
                        <div class="thanks">
                            <h3>@Model.ThanksHeader</h3>
                            @Model.ThanksBodytext
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div id="map" style="height: 500px; width: 100%; margin: 50px 0 -20px;"></div>
    </div>

</div>

@section Scripts{
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyA9PGAWyEx1nGnWPp-Fmc9gvT_c1OocXtI"></script>
    <script>
        function CustomMarker(e, t, i) {
            this.latlng = e, this.args = i, this.setMap(t)
        }
        function initMap() {
            {
                var lat = "55.380710";
                var lon = "10.410847";
                var e = new google.maps.LatLng(lat, lon), t = new google.maps.LatLng(lat,lon), i = {
                    center: t,
                    styles: mapStyles,
                    scrollwheel: false,
                    draggable: true,
                    zoom: 8,
                    streetViewControl: false,
                    mapTypeControl: false,
                }, n = new google.maps.Map(document.getElementById("map"), i);
                new CustomMarker(e, n, {})
            }
        }
        CustomMarker.prototype = new google.maps.OverlayView, CustomMarker.prototype.draw = function() {
            var e = this, t = this.div;
            if (!t) {
                t = this.div = document.createElement("div"), t.className = "map-marker", "undefined" != typeof e.args.marker_id && (t.dataset.marker_id = e.args.marker_id), google.maps.event.addDomListener(t, "click", function() {
                    google.maps.event.trigger(e, "click")
                });
                var i = this.getPanes();
                i.overlayImage.appendChild(t)
            }
            var n = this.getProjection().fromLatLngToDivPixel(this.latlng);
            n && (t.style.left = n.x + "px", t.style.top = n.y + "px")
        }, CustomMarker.prototype.remove = function() {
            this.div && (this.div.parentNode.removeChild(this.div), this.div = null)
        }, CustomMarker.prototype.getPosition = function() {
            return this.latlng
        };

        var mapStyles = [
            {
                "featureType": "administrative",
                "elementType": "all",
                "stylers": [{ "visibility": "on" }, { "saturation": -100 }, { "lightness": 20 }]
            }, {
                "featureType": "road",
                "elementType": "all",
                "stylers": [{ "visibility": "on" }, { "saturation": -100 }, { "lightness": 40 }]
            }, {
                "featureType": "water",
                "elementType": "all",
                "stylers": [{ "visibility": "on" }, { "saturation": -10 }, { "lightness": 30 }]
            }, {
                "featureType": "landscape.man_made",
                "elementType": "all",
                "stylers": [{ "visibility": "simplified" }, { "saturation": -60 }, { "lightness": 10 }]
            }, {
                "featureType": "landscape.natural",
                "elementType": "all",
                "stylers": [{ "visibility": "simplified" }, { "saturation": -60 }, { "lightness": 60 }]
            }, {
                "featureType": "poi",
                "elementType": "all",
                "stylers": [{ "visibility": "on" }, { "saturation": -100 }, { "lightness": 60 }]
            }, {
                "featureType": "transit",
                "elementType": "all",
                "stylers": [{ "visibility": "off" }, { "saturation": -100 }, { "lightness": 60 }]
            }
        ];
        initMap();
    </script>
}

GoDinghy.app/Views/CustomerListPage.cshtml
@model CustomerListPageModel
    
<div class="customerpage">
    <div class="container-fluid">
        <div class="container text-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.Header</h1>
                    @Model.Bodytext
                </div>
            </div>
        </div>
    </div>
</div>

GoDinghy.app/Views/Employeespage.cshtml
@model EmployeespageModel

<div class="employeespage">
    <div class="container-fluid">
        <div class="banner" style="background-image: url(@Model.Banner)">

        </div>
        <div class="container text-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="text">
                        <h1>@Model.Header</h1>
                    </div>
                </div>
                <div class="col-md-12">
                    @Model.Bodytext
                </div>
                <div class="col-md-12">
                    <div class="row">
                        @foreach (var employee in Model.Employees)
                        {
                            <div class="col-md-4">
                                <a href="@employee.Url">
                                    <img src="@employee.Image" alt="@employee.Name" title="@employee.Name" />
                                </a>
                                    <p>@employee.Email</p>
                                    <p>
                                        @employee.Title
                                    </p>
                                    <p>
                                        <a href="mailto:@employee.Email">@employee.Email</a>
                                    </p>
                                    <p><a href="Tel:@employee.Phone">@employee.Phone</a></p>
                                
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

GoDinghy.app/Views/Frontpage.cshtml
@model FrontpageModel
<div class="frontpage">
    <div class="container-fluid">
        <div class="banner" style="background-image: url(@Model.Banner)">
            <div class="container text-wrapper">
                <div class="row">
                    <div class="col-md-10">
                        <div class="text">
                            <h1>@Model.Header</h1>
                            @Model.Teaser
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Model.Grid
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                
            </div>
        </div>
    </div>



</div>

GoDinghy.app/Views/Layout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = null;
}

GoDinghy.app/Views/Memberpage.cshtml
@model MemberpageModel

<div class="customerpage">
    <div class="container-fluid">
        <div class="container text-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.Header</h1>
                    @Model.Bodytext
                </div>
                <div class="col-md-12">
                    @using (Ajax.BeginForm("OpenLogFile", "MemberSurface", null))
                    {
                        <input type="submit" value="Åbn login log" />
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @Html.Partial("_CreateMember", Model.MemberModel)
                </div>
                <div class="col-md-12" id="thanks">
                    <p>teakketekst</p>
                </div>
            </div>
        </div>
    </div>
</div>

GoDinghy.app/Views/SearchPage.cshtml
@using System.Linq
@model SearchPageModel
	
<h1>@Model.Header</h1>
@Model.BodyText

@if (Model.SearchItems.Any())
{
	<ol id="searchresults">
		@foreach (var item in Model.SearchItems)
		{
			<li>
				<a href="@item.URL">@item.Title</a>
				<p>@item.Description</p>
			</li>
		}
	</ol>
}
else
{
	<h3>Din søgning gav ikke nogen resultater</h3>
}

GoDinghy.app/Views/Standard404.cshtml
@model ErrorPageModel

<div class="textpage">
    <div class="container-fluid">
        <div class="banner" style="background-image: url(@Model.Banner)">

        </div>
        <div class="container text-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="text">
                        <h1>@Model.Header</h1>
                        @Model.Bodytext
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

GoDinghy.app/Views/Textpage.cshtml
@model TextpageModel

<div class="textpage">
    <div class="container-fluid">
        <div class="banner" style="background-image: url(@Model.Banner)">

        </div>
        <div class="container text-wrapper">
            <div class="row">
                <div class="col-md-12">
                    <div class="text">
                        <h1>@Model.Header</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Model.Grid
</div>

GoDinghy.app/Views/employeepage.cshtml
@model EmployeepageModel

<div class="employeepage">
        
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img src="@Model.Image" alt="@Model.Name" title="@Model.Name"/>
                    
                </div>
                <div class="col-md-6">
                    <p>@Model.Name</p>
                    <p>@Model.Title</p>
                    <p><a href="mailto:@Model.Email">@Model.Email</a></p>
                    <p><a href="Tel:@Model.Phone">@Model.Phone</a></p>
                    <hr/>
                    @Model.Description
                </div>
            </div>
        </div>
</div>